email_writer_task:
  description: >
    Create the BEST job aplication email
  expected_output: >
    Allways write the email in the company/resume native language.
    Using the information from the files {crew_generated_resume_path} and {company_report_path}, create the best job aplication
    email that uses the company information to highlight the applicant skills.
    If your email it's not the best, your reviewer will ask yout to improve your writing, when this occurs,
    you have don't have to rewrite the email, just add/change the content based on the application examiner thoughts.
    {user_considerations_for_email_crew}
    Formatted as markdown without '```'
    Allways write the email in the company/resume native language.
  agent: email_writer

application_examiner_task:
  description: >
    Read the job application email and evaluate it from 0 to 10 pointing out improvements for the email.
    If your evaluation is lower than 9, you have to improve it with your thoughts.
  expected_output: >
    Allways write the email in the company/resume native language.
    A evaluation of the job application email from 0 to 10.
    If the evaluation is lower than 9, you have to write the email in the company/resume native language with your thoughts.
    If the evaluation is higher than 9, return the email as it is.
    Don't include your evaluation notes in the email.
    Formatted as markdown without '```'
    Allways write the email in the company/resume native language.
  agent: application_examiner
  context:
    - email_writer_task
